const express = require("express");
const logger = require("./utils/looger");
const ErrorRoute = require("./utils/error");
const morgan = require("morgan");
const BlogRouter = require("./routes/blogroutes");
const app = express();
app.use(express.json());
app.use(logger);
app.use(morgan("dev"));
app.use("/Blog", BlogRouter);
app.use(ErrorRoute);
module.exports = app;
