const express = require("express");
const logger = require("./utils/looger");
const ErrorRoute = require("./utils/error");
const morgan = require("morgan");
const userRouter = require("./routes/userroutes");
const app = express();
app.use(express.json());
app.use(logger);
app.use(morgan("dev"));
app.use("/user", userRouter);
app.use(ErrorRoute);
module.exports = app;
